watch:
  - name: acpi
    run:
      program:
        binary: acpi
        args: ["-V"]
    schedule:
      period: 1m
    analyse:
      - name: temperature
        run:
          shell: "grep \"^Thermal 0:\" | head -1 | sed \"s/.*ok, //\" | sed \"s/[^0-9.].*//g\""
  - name: df
    run:
      shell: "df"
    schedule:
      random:
        min: 10s
        max: 120s
  - name: date
    run:
      shell: "date +%s"
    schedule:
      period: 5s
  - name: trivialNode
    run:
      do-not-run: true
    schedule:
      period: 5s
  - name: sleep5s
    run:
      shell: "sleep 5s"
      timeout: 2s
    schedule:
      period: 10s
  - name: mefi
    run:
      program:
        binary: "./examples/scripts/scrape.py"
        args: ["http://www.metafilter.com"]
      timeout: 30s
    schedule:
      period: 10m
    analyse:
      - name: comment_counts
        run:
          program:
            binary: "./examples/scripts/mefi_comment_count.py"
        analyse:
          - name: popular_threads
            run:
              python3: "rv = {k: n for k, n in json.load(sys.stdin).items() if n > 100}; print(rv) if rv else None"
            triggers:
              - name: popular_fpps_trigger
                period: 8h
                run:
                  shell: "cat >> /tmp/watcher-trigger-example-mefi-popular-fpps.generated.txt"
