watch:
  - name: acpi
    run:
      program:
        binary: acpi
        args: ["-V"]
    schedule:
      period: 1m
    analyse:
      - name: temperature
        run:
          shell: "grep \"^Thermal 0:\" | head -1 | sed \"s/.*ok, //\" | sed \"s/[^0-9.].*//g\""
  - name: df
    run:
      shell: "df"
    schedule:
      random:
        min: 10s
        max: 120s
  - name: date
    run:
      shell: "date +%s"
    schedule:
      period: 5s
  - name: sleep5s
    run:
      shell: "sleep 5s"
      timeout: 2s
    schedule:
      period: 10s

