watch:
  - name: acpi
    run:
      program:
        binary: acpi
        args: ["-V"]
    schedule:
      period: 1m
    analyse:
      - name: temperature
        run:
          shell: "grep \"^Thermal 0:\" | head -1 | sed \"s/.*ok, //\" | sed \"s/[^0-9.].*//g\""
  - name: df
    run:
      shell: "df"
    schedule:
      random:
        min: 10s
        max: 120s
  - name: date
    run:
      shell: "date +%s"
    schedule:
      period: 5s
  - name: sleep5s
    run:
      shell: "sleep 5s"
      timeout: 2s
    schedule:
      period: 10s
  - name: mefi
    run:
      program:
        binary: "./examples/scripts/scrape.py"
        args: ["http://www.metafilter.com"]
      timeout: 30s
    schedule:
      period: 10m
    analyse:
      - name: comment_counts
        run:
          program:
            binary: "./examples/scripts/mefi_comment_count.py"
        analyse:
          - name: popular_thread
            run:
              program:
                binary: python3
                args: ["-c", "import json; import sys; json.dump(max(json.load(sys.stdin).values()) > 100, sys.stdout)"]
